name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
      with:
        working-directory: .
      env:
       AUTH_PROVIDERS: ${{ secrets.AUTH_PROVIDERS }}
    - run: "echo \"$AUTH_PROVIDERS\" > ../auth-providers.ts"
    - run: "ls -la .."     
    - run: yarn build
